spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai-rent-platform
    username: root
    password: 123456
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
  data:
    redis:
      host: 192.168.246.130
      port: 6379

  mail:
    host: smtp.qq.com
    username: ${EMAIL}
    password: ${PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    host: 192.168.246.130
    port: 5672
    username: guest
    password: guest